// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import I18nProvider from "./i18n-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Admin Starter",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={cn(inter.className, "bg-background")}>
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
